// <auto-generated />
using System;
using BankSystemDataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankSystem.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240906230724_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankSystemDataAccess.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Clients__7AD04FF10A571613");

                    b.HasIndex(new[] { "PersonId" }, "IX_Clients_PersonId");

                    b.HasIndex(new[] { "PersonId" }, "UQ__Clients__AA2FFB84B567F7DF")
                        .IsUnique();

                    b.HasIndex(new[] { "AccountNumber" }, "UQ__Clients__BE2ACD6FC14AB4AE")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint")
                        .HasComment("0 => Male \r\n1 => Female");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Persons__AA2FFB8516B9919B");

                    b.ToTable("People");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.RegisterLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RegisterLoginsDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Register__A13C533E51AEE68A");

                    b.HasIndex(new[] { "UserId" }, "IX_RegisterLogins_UserId");

                    b.ToTable("RegisterLogins");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.TransfersLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("DestinationBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("DestinationClientId")
                        .HasColumnType("int");

                    b.Property<decimal>("SourceBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SourceClientId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_TransfersLog");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_TransfersLogs_CreatedByUserId");

                    b.HasIndex(new[] { "DestinationClientId" }, "IX_TransfersLogs_DestinationClientId");

                    b.HasIndex(new[] { "SourceClientId" }, "IX_TransfersLogs_SourceClientId");

                    b.ToTable("TransfersLogs");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Users__1788CCACAB45311C");

                    b.HasIndex(new[] { "PersonId" }, "IX_Users_PersonId");

                    b.HasIndex(new[] { "PersonId" }, "UQ__Users__AA2FFB84DC0D1567")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__Users__C9F28456AD961997")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.Views.ClientInfoView", b =>
                {
                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable((string)null);

                    b.ToView("vw_ClientInfo", (string)null);
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.Views.RegisterLoginsInfoView", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable((string)null);

                    b.ToView("vw_RegisterLoginsInfo", (string)null);
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.Views.UserInfoView", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable((string)null);

                    b.ToView("vw_UserInfo", (string)null);
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.Client", b =>
                {
                    b.HasOne("BankSystemDataAccess.Entities.Person", "Person")
                        .WithOne("Client")
                        .HasForeignKey("BankSystemDataAccess.Entities.Client", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__Clients__Perso__398D8EEE");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.RegisterLogin", b =>
                {
                    b.HasOne("BankSystemDataAccess.Entities.User", "User")
                        .WithMany("RegisterLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__RegisterL__UserI__02FC7413");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.TransfersLog", b =>
                {
                    b.HasOne("BankSystemDataAccess.Entities.User", "CreatedByUser")
                        .WithMany("TransfersLogs")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TransfersLogs_Users");

                    b.HasOne("BankSystemDataAccess.Entities.Client", "DestinationClient")
                        .WithMany("TransfersLogDestinationClients")
                        .HasForeignKey("DestinationClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TransfersLog_Clients1");

                    b.HasOne("BankSystemDataAccess.Entities.Client", "SourceClient")
                        .WithMany("TransfersLogSourceClients")
                        .HasForeignKey("SourceClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TransfersLog_Clients");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DestinationClient");

                    b.Navigation("SourceClient");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.User", b =>
                {
                    b.HasOne("BankSystemDataAccess.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("BankSystemDataAccess.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__Users__PersonID__3C69FB99");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.Client", b =>
                {
                    b.Navigation("TransfersLogDestinationClients");

                    b.Navigation("TransfersLogSourceClients");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.Person", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankSystemDataAccess.Entities.User", b =>
                {
                    b.Navigation("RegisterLogins");

                    b.Navigation("TransfersLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
